SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS TBL_CATALOG_A; 
 
CREATE TABLE TBL_CATALOG_A (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  sku_id VARCHAR(12) NOT NULL,
  product_desc VARCHAR(250)  NOT NULL,
  catalog_name VARCHAR(1)  NOT NULL
);

DROP TABLE IF EXISTS TBL_SUPPLIER;
 
CREATE TABLE TBL_SUPPLIER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  supplier_id INT NOT NULL,
  supplier_name VARCHAR(250) NOT NULL,
  supplier_cmpny VARCHAR(1) NOT NULL
  );
  


DROP TABLE IF EXISTS TBL_SUP_CAT_BARCODES;
 
CREATE TABLE TBL_SUP_CAT_BARCODES(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  sku_id VARCHAR(12) NOT NULL,
  bar_code VARCHAR(40) NOT NULL,
 comp_name VARCHAR(1) NOT NULL,
 catalog_id INT,
 supplier_id INT);


ALTER TABLE TBL_SUP_CAT_BARCODES ADD FOREIGN KEY(catalog_id) REFERENCES TBL_CATALOG_A(id);
ALTER TABLE TBL_SUP_CAT_BARCODES ADD FOREIGN KEY(supplier_id) REFERENCES TBL_SUPPLIER(id);
SET FOREIGN_KEY_CHECKS=1;
